### ISSUE TITLE
Fix typo.

### ISSUE THREAD

**Issue by mhs54321** [typiconman/ponomar#14]
Dear Ponomar:

http://www.ponomar.net/cgi-bin/bible.cgi?menu=no&book=I%20Cor&reading=9:1

There is an extra "am" within the beginning of that verse. This typo exists in many online versions of KJV text. However, the error is not present in the authoritative Cambridge edition and also not present in the Original: https://www.kingjamesbibleonline.org/1-Corinthians-Chapter-9_Original-1611-KJV/

A quick `diff` of the text against a good version revealed the problem (seems to be only about 2 or 3 bona fide typos).

I've opened a pull request. Feel free to pull the corrected reading.
In Christ,
Mark

**Comment by typiconman** [comment]
I think this has been corrected, yes?
